using Emissions
using Test

include("test_plumerise.jl")
include("test_constants.jl")
include("test_types.jl")
include("test_ff10.jl")
include("test_io.jl")
include("test_spatial.jl")
include("test_surrogates.jl")
include("test_output.jl")
include("test_pipeline.jl")
include("test_workflow.jl")
include("test_temporal.jl")
include("test_merge.jl")
include("test_speciation.jl")
include("test_controls.jl")
include("test_elevpoint.jl")
include("test_laypoint.jl")
include("test_regridding.jl")
include("test_biogenic.jl")
include("test_validation.jl")
include("test_orl.jl")
include("test_report.jl")
include("test_griddesc.jl")
include("test_ioapi.jl")
include("test_integration.jl")
include("test_pipeline_integration.jl")
include("test_smoke_example.jl")
# Enhanced SMOKE validation tests - now enabled by default for comprehensive validation
include("test_smoke_comprehensive_validation.jl")
include("test_smoke_additional_validation.jl")
include("test_smoke_enhanced_validation.jl")
include("test_smoke_sector_extensibility.jl")
